import "/data/data/com.termux/files/home/dvnge-website/node_modules/@vuepress/highlighter-helper/dist/client/styles/base.css"
import "/data/data/com.termux/files/home/dvnge-website/node_modules/@vuepress/plugin-prismjs/dist/client/styles/shades-of-purple.css"
import "/data/data/com.termux/files/home/dvnge-website/node_modules/@vuepress/highlighter-helper/dist/client/styles/line-numbers.css"
import "/data/data/com.termux/files/home/dvnge-website/node_modules/@vuepress/highlighter-helper/dist/client/styles/notation-highlight.css"
import "/data/data/com.termux/files/home/dvnge-website/node_modules/@vuepress/highlighter-helper/dist/client/styles/code-block-title.css"